default_platform(:mac)

platform :mac do
  desc "Build and upload to TestFlight"
  lane :testflight_upload do
    api_key = app_store_connect_api_key(
      key_id: "<app-store-key-id>",
      issuer_id: "<app-store-issuer-id>",
      key_filepath: File.expand_path("$APPSTORECONNECT_CONFIG"),
      in_house: false
    )

    build_app(
      project: "WaiSay.xcodeproj",
      scheme: "WaiSay",
      export_method: "app-store",
      output_directory: "build",
      output_name: "WaiSay.pkg",
      destination: "generic/platform=macOS",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      apple_id: "6761768729",
      skip_waiting_for_build_processing: true
    )
  end
end
