default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :testflight_upload do
    api_key = app_store_connect_api_key(
      key_id: "TND8C962YA",
      issuer_id: "db1b8a2b-2870-44dc-baf5-bbc2a17db1a3",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_TND8C962YA.p8"),
      in_house: false
    )

    build_app(
      project: "WaiSayiOS.xcodeproj",
      scheme: "WaiSay",
      export_method: "app-store",
      output_directory: "build",
      output_name: "WaiSay.ipa",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
