"""add commitments, digital_agents, user_apps, app_items

Revision ID: 869f5f0a48e5
Revises: 000011
Create Date: 2026-03-30 18:51:27.174501+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '869f5f0a48e5'
down_revision: Union[str, None] = '000011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('who', sa.String(length=200), nullable=False),
    sa.Column('what', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commitments_user_direction', 'commitments', ['user_id', 'direction'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.create_index('ix_commitments_user_status', 'commitments', ['user_id', 'status'], unique=False)
    op.create_table('digital_agents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('tools', sa.String(length=500), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=50), nullable=True),
    sa.Column('delivery_channel', sa.String(length=50), nullable=False),
    sa.Column('delivery_target', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('max_tokens_per_run', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_digital_agents_next_run', 'digital_agents', ['next_run_at', 'status'], unique=False)
    op.create_index(op.f('ix_digital_agents_user_id'), 'digital_agents', ['user_id'], unique=False)
    op.create_index('ix_digital_agents_user_status', 'digital_agents', ['user_id', 'status'], unique=False)
    op.create_table('user_apps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('schema_def', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('app_url', sa.String(length=500), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_apps_user_id'), 'user_apps', ['user_id'], unique=False)
    op.create_index('ix_user_apps_user_name', 'user_apps', ['user_id', 'name'], unique=True)
    op.create_table('app_items',
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['user_apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_items_app_id'), 'app_items', ['app_id'], unique=False)
    op.create_index('ix_app_items_data', 'app_items', ['data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_items_data', table_name='app_items', postgresql_using='gin')
    op.drop_index(op.f('ix_app_items_app_id'), table_name='app_items')
    op.drop_table('app_items')
    op.drop_index('ix_user_apps_user_name', table_name='user_apps')
    op.drop_index(op.f('ix_user_apps_user_id'), table_name='user_apps')
    op.drop_table('user_apps')
    op.drop_index('ix_digital_agents_user_status', table_name='digital_agents')
    op.drop_index(op.f('ix_digital_agents_user_id'), table_name='digital_agents')
    op.drop_index('ix_digital_agents_next_run', table_name='digital_agents')
    op.drop_table('digital_agents')
    op.drop_index('ix_commitments_user_status', table_name='commitments')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index('ix_commitments_user_direction', table_name='commitments')
    op.drop_table('commitments')
    # ### end Alembic commands ###
