default_platform(:ios)

platform :ios do
  desc "Upload iOS metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "<app-store-key-id>",
      issuer_id: "<app-store-issuer-id>",
      key_filepath: File.expand_path("$APPSTORECONNECT_CONFIG"),
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_identifier: "is.waiwai.say",
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end

platform :mac do
  desc "Upload macOS metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "<app-store-key-id>",
      issuer_id: "<app-store-issuer-id>",
      key_filepath: File.expand_path("$APPSTORECONNECT_CONFIG"),
      in_house: false
    )

    deliver(
      api_key: api_key,
      platform: "osx",
      app_identifier: "is.waiwai.say",
      screenshots_path: "fastlane/screenshots_macos",
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
