default_platform(:ios)

platform :ios do
  desc "Upload iOS metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "TND8C962YA",
      issuer_id: "db1b8a2b-2870-44dc-baf5-bbc2a17db1a3",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_TND8C962YA.p8"),
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_identifier: "is.waiwai.say",
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end

platform :mac do
  desc "Upload macOS metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "TND8C962YA",
      issuer_id: "db1b8a2b-2870-44dc-baf5-bbc2a17db1a3",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_TND8C962YA.p8"),
      in_house: false
    )

    deliver(
      api_key: api_key,
      platform: "osx",
      app_identifier: "is.waiwai.say",
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
