default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :testflight_upload do
    api_key = app_store_connect_api_key(
      key_id: "<app-store-key-id>",
      issuer_id: "<app-store-issuer-id>",
      key_filepath: File.expand_path("$APPSTORECONNECT_CONFIG"),
      in_house: false
    )

    build_app(
      project: "WaiComputeriOS.xcodeproj",
      scheme: "WaiComputer",
      export_method: "app-store",
      output_directory: "build",
      output_name: "WaiComputer.ipa",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
