#!/usr/bin/env bash
# One-command self-host setup for WaiComputer.
#
# Run this on the server (a fresh Ubuntu/Debian VPS with Docker, or any
# machine with Docker Desktop for a local install):
#
#   ./scripts/self-host-setup.sh
#
# It asks for your domain and API keys, generates strong secrets, writes
# backend/.env.selfhost + a Caddyfile for your domain (HTTPS is automatic
# via Let's Encrypt), builds the stack, and waits for /health.
#
# Non-interactive use: pre-set the variables and pass --yes, e.g.
#   WAI_DOMAIN=brain.example.com DEEPGRAM_API_KEY=… OPENAI_API_KEY=… \
#   CEREBRAS_API_KEY=… ./scripts/self-host-setup.sh --yes
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
ENV_FILE="$BACKEND_DIR/.env.selfhost"
CADDYFILE="$BACKEND_DIR/Caddyfile.selfhost"
ASSUME_YES=0
[[ "${1:-}" == "--yes" || "${1:-}" == "-y" ]] && ASSUME_YES=1

say()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

prompt() { # prompt VAR "label" "default" required(0/1) secret(0/1)
  local var="$1" label="$2" default="$3" required="$4" secret="${5:-0}" current value
  current="${!var:-}"
  if [[ -n "$current" ]]; then return 0; fi
  if [[ "$ASSUME_YES" == 1 ]]; then
    if [[ "$required" == 1 && -z "$default" ]]; then
      fail "$var is required (set it as an environment variable for --yes mode)"
    fi
    printf -v "$var" '%s' "$default"
    return 0
  fi
  while true; do
    if [[ "$secret" == 1 ]]; then
      read -r -s -p "$label${default:+ [$default]}: " value; echo
    else
      read -r -p "$label${default:+ [$default]}: " value
    fi
    value="${value:-$default}"
    if [[ -n "$value" || "$required" == 0 ]]; then
      printf -v "$var" '%s' "$value"
      return 0
    fi
    echo "  This value is required."
  done
}

# --- 1. Prerequisites --------------------------------------------------------
say "Checking prerequisites"
command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "The Docker Compose plugin is missing. Install docker-compose-plugin."
command -v openssl >/dev/null 2>&1 || fail "openssl is required to generate secrets."
ok "Docker $(docker --version | sed 's/Docker version //;s/,.*//') + Compose ready"

# --- 2. Configuration --------------------------------------------------------
say "Configuration (Enter accepts the default)"
echo "  Use a real domain pointing at this server for automatic HTTPS,"
echo "  or 'localhost' for a local, HTTP-only install."
prompt WAI_DOMAIN "Domain (e.g. brain.example.com, or localhost)" "localhost" 1
echo
echo "  Required keys — the product can't transcribe or summarize without them:"
echo "   · Deepgram (speech-to-text):        https://console.deepgram.com"
echo "   · OpenAI (companion + embeddings):  https://platform.openai.com"
echo "   · Cerebras (summaries + cleanup):   https://cloud.cerebras.ai"
prompt DEEPGRAM_API_KEY "Deepgram API key" "" 1 1
prompt OPENAI_API_KEY "OpenAI API key" "" 1 1
prompt CEREBRAS_API_KEY "Cerebras API key" "" 1 1
echo
echo "  Optional keys (Enter to skip — the feature stays off with a clear in-app error):"
echo "   · ElevenLabs: realtime voice conversations with Wai"
echo "   · Resend:     magic-link sign-in emails (password sign-in always works)"
prompt ELEVENLABS_API_KEY "ElevenLabs API key (optional)" "" 0 1
prompt RESEND_API_KEY "Resend API key (optional)" "" 0 1

if [[ "$WAI_DOMAIN" == "localhost" ]]; then
  PUBLIC_URL="http://localhost"
  COOKIE_SECURE="false"
else
  PUBLIC_URL="https://$WAI_DOMAIN"
  COOKIE_SECURE="true"
fi

# --- 3. Secrets + .env -------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
  say "Keeping the existing $ENV_FILE (delete it to regenerate)"
else
  say "Writing $ENV_FILE with generated secrets"
  JWT_SECRET="$(openssl rand -hex 32)"
  PG_PASSWORD="$(openssl rand -hex 24)"
  cat > "$ENV_FILE" <<ENV
# Generated by scripts/self-host-setup.sh — your server, your data.
POSTGRES_USER=waicomputer
POSTGRES_PASSWORD=$PG_PASSWORD
POSTGRES_DB=waicomputer
DATABASE_URL=postgresql+asyncpg://waicomputer:$PG_PASSWORD@db:5432/waicomputer

JWT_SECRET=$JWT_SECRET
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=10080
AUTH_COOKIE_SECURE=$COOKIE_SECURE
AUTH_COOKIE_DOMAIN=$WAI_DOMAIN

FRONTEND_URL=$PUBLIC_URL
PUBLIC_BASE_URL=$PUBLIC_URL
CORS_ORIGINS=["$PUBLIC_URL"]
DEPLOYMENT_MODE=self_host

DEEPGRAM_API_KEY=$DEEPGRAM_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
CEREBRAS_API_KEY=$CEREBRAS_API_KEY
ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY
RESEND_API_KEY=$RESEND_API_KEY

REDIS_URL=redis://redis:6379/0
UPLOAD_STAGING_DIR=/var/lib/waicomputer/uploads
SUMMARY_AUDIO_STORAGE_DIR=/var/lib/waicomputer/summary-audio
ENV
  chmod 600 "$ENV_FILE"
  ok "Secrets generated (JWT + database password)"
fi

# --- 4. Caddyfile for the domain ----------------------------------------------
say "Writing $CADDYFILE for $WAI_DOMAIN"
SITE="$WAI_DOMAIN"
[[ "$WAI_DOMAIN" == "localhost" ]] && SITE="http://localhost"
cat > "$CADDYFILE" <<CADDY
# Generated by scripts/self-host-setup.sh.
# A real domain gets automatic HTTPS from Let's Encrypt; point the domain's
# A/AAAA records at this server before running setup.
$SITE {
    handle /api/* {
        reverse_proxy api:8000
    }

    handle /mcp {
        reverse_proxy api:8000
    }

    handle /.well-known/oauth-* {
        reverse_proxy api:8000
    }

    handle /authorize {
        reverse_proxy api:8000
    }

    handle /token {
        reverse_proxy api:8000
    }

    handle /revoke {
        reverse_proxy api:8000
    }

    @mcpRegistration {
        method POST OPTIONS
        path /register
    }
    handle @mcpRegistration {
        reverse_proxy api:8000
    }

    @health path /health /health/*
    handle @health {
        reverse_proxy api:8000
    }

    handle {
        reverse_proxy web:3000
    }

    header {
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        -Server
    }

    request_body {
        max_size 200MB
    }
}
CADDY
ok "Reverse proxy configured"

# --- 5. Build + start ----------------------------------------------------------
say "Building and starting the stack (first build takes a few minutes)"
cd "$BACKEND_DIR"
GIT_SHA="$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo selfhost)"
WAICOMPUTER_ENV_FILE="$ENV_FILE" GIT_SHA="$GIT_SHA" docker compose \
  --env-file "$ENV_FILE" \
  -f docker-compose.yml \
  -f docker-compose.selfhost.yml \
  up -d --build

# --- 6. Health check -----------------------------------------------------------
say "Waiting for the API to come up"
for i in $(seq 1 60); do
  if docker exec waicomputer-api curl -fsS http://localhost:8000/health >/dev/null 2>&1; then
    ok "API is healthy"
    echo
    ok "WaiComputer is running at $PUBLIC_URL"
    echo "   · Create your account:        $PUBLIC_URL/register"
    echo "   · Connect agents over MCP:    $PUBLIC_URL/mcp  (Settings → MCP has copy-paste setup)"
    echo "   · Telegram bot, native apps:  see docs/self-hosting.md"
    exit 0
  fi
  sleep 5
done
fail "The API did not become healthy in 5 minutes. Check: docker logs waicomputer-api"
